[versions]
autoService = "1.0.1"

googleJavaFormat = "1.15.0"
ktlint = "0.48.2"

[libraries]
autoService = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
autoService-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }
compileTesting = "com.google.testing.compile:compile-testing:0.21.0"
junit = "junit:junit:4.13.2"
truth = "com.google.truth:truth:1.1.3"

# Used in below bundle
errorprone-core = "com.google.errorprone:error_prone_core:2.18.0"
nullaway = "com.uber.nullaway:nullaway:0.10.8"

[bundles]
errorprone = [ "errorprone-core", "nullaway" ]

[plugins]
errorprone = "net.ltgt.errorprone:3.0.1"
nullaway = "net.ltgt.nullaway:1.5.0"
spotless = "com.diffplug.spotless:6.13.0"
